import fs from "fs";
import path from "path";
import matter from "gray-matter";

const contentDir = path.join(process.cwd(), "content");

function getFilesRecursively(dir) {
  let results = [];
  if (!fs.existsSync(dir)) return [];
  const list = fs.readdirSync(dir);
  list.forEach((file) => {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);
    if (stat && stat.isDirectory()) {
      results = results.concat(getFilesRecursively(filePath));
    } else if (file.endsWith(".mdx") || file.endsWith(".md") || file.endsWith(".txt")) {
      results.push(filePath);
    }
  });
  return results;
}

const files = getFilesRecursively(contentDir);
const report = [];

console.log(`Checking ${files.length} files...`);

files.forEach((filePath) => {
  const content = fs.readFileSync(filePath, "utf8");
  const { data } = matter(content);
  const relativePath = path.relative(contentDir, filePath);
  
  const issues = [];
  
  if (!data.description) {
    issues.push("Missing description");
  } else if (data.description.toLowerCase().includes("reference notes for")) {
    issues.push("Generic description (autogenerated fallback)");
  }
  
  if (!data.tags || data.tags.length === 0) {
    issues.push("Missing tags");
  }
  
  if (issues.length > 0) {
    report.push({
      file: relativePath,
      issues: issues,
    });
  }
});

if (report.length === 0) {
  console.log("No frontmatter issues found. All content adheres to quality standards.");
} else {
  console.log("FILE | ISSUES");
  console.log("------------------");
  report.forEach(item => {
    console.log(`${item.file} | ${item.issues.join(", ")}`);
  });
}
